# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "pwa/register", to: "pwa/register.js"
pin "chartkick", to: "chartkick.js"
pin "Chart.bundle", to: "Chart.bundle.js"
pin "controllers/appointment_summary_controller", to: "controllers/appointment_summary_controller.js"
pin "controllers/dependent_select_controller", to: "controllers/dependent_select_controller.js"
pin "controllers/logo_preview_controller", to: "controllers/logo_preview_controller.js"
pin "controllers/navbar_controller", to: "controllers/navbar_controller.js"
pin "controllers/role_selector_controller", to: "controllers/role_selector_controller.js"
pin "controllers/service_templates_controller", to: "controllers/service_templates_controller.js"
pin "controllers/sidebar_controller", to: "controllers/sidebar_controller.js"
pin "controllers/stripe_payment_controller", to: "controllers/stripe_payment_controller.js"
pin "controllers/widget_tools_controller", to: "controllers/widget_tools_controller.js"
